### ISSUE TITLE
[Feature Request] Ability to pause tool

### ISSUE THREAD

**Issue by Mantas-2155X** [cwkx/keym#2]
Hello, thanks for making this tool, it is quite useful.

In my opinion having a way of allowing normal keyboard usage to for example send a message, and then switch back to keyboard-mouse control would be great instead of having to close and start the application again.

Could be something as simple as clicking ESC to toggle.

**Comment by cwkx** [comment]
Hi, this is a non-goal as you can achieve this functionality through most window managers or via ``xbindkeys`` e.g. by putting:
```
"keym"
    m:0x8 + c:58
    Alt + m
```
in your ``.xbindkeysrc`` to launch it with Alt+M
