### ISSUE TITLE
custom control

### ISSUE THREAD

**Issue by ajfpay** [cwkx/keym#4]
I love this app, acceleration very good, but if I want use "wasd" for write, must close this app, and If want to use must be On again.
Can this app custom like Super+ijkl for move? If that's the case I can still use the function from "ijkl" to type

**Comment by cwkx** [comment]
Thanks. This is a non-goal for me but it should be possible to hack the code to your needs (I didn't write it this way in spirit of the UNIX philosophy, e.g. when the code is not being used its not in memory - just running it in a toggle launched from ``xbindkeys``)
```
"keym"
    m:0x8 + c:58
    Alt + m
```
in the ``.xbindkeysrc`` to launch it with Alt+M.

However, to make it work as you intended - where you hold a key to grab focus/move mouse then release the key to give back standard keyboard control - is probably best to write this so the tool is always running in the background, then add an if statement around XGrabKeyboard and the mouse movement logic - so it shouldn't be that difficult to hack the code to work as you described.
